name: Build Gradle and Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'
jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle wrapper
        run: ./gradlew build

      - name: Upload all artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: |
            cli/build/libs/mcrpx-cli-*.jar
            gui/build/libs/mcrpx-gui-*.jar